{% set name = "sacremoses" %}
{% set version = "0.0.45" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 58176cc28391830789b763641d0f458819bebe88681dac72b41a19c0aedc07e9

build:
  noarch: python
  number: 2
  string: h{{ PKG_HASH }}py_{{ PKG_BUILDNUM }}
  entry_points:
    - sacremoses=sacremoses.cli:cli
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip {{ pip }}
    - python
  run:
    - click {{ click }}
    - joblib {{ joblib }}
    - python
    - regex {{ regex }}
    - six {{ six }}
    - tqdm {{ tqdm }}

test:
  imports:
    - sacremoses

about:
  home: https://github.com/alvations/sacremoses
  license: LGPL-2.1-or-later
  license_family: LGPL
  license_file: LICENSE
  summary: SacreMoses
  description: MosesTokenizer in Python

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
